package com.tutor.auth0r.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IdentityCardAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityCardAllPropertiesEquals(IdentityCard expected, IdentityCard actual) {
        assertIdentityCardAutoGeneratedPropertiesEquals(expected, actual);
        assertIdentityCardAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityCardAllUpdatablePropertiesEquals(IdentityCard expected, IdentityCard actual) {
        assertIdentityCardUpdatableFieldsEquals(expected, actual);
        assertIdentityCardUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityCardAutoGeneratedPropertiesEquals(IdentityCard expected, IdentityCard actual) {
        assertThat(expected)
            .as("Verify IdentityCard auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityCardUpdatableFieldsEquals(IdentityCard expected, IdentityCard actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdentityCardUpdatableRelationshipsEquals(IdentityCard expected, IdentityCard actual) {}
}
