package com.tutor.auth0r.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MediaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAllPropertiesEquals(Media expected, Media actual) {
        assertMediaAutoGeneratedPropertiesEquals(expected, actual);
        assertMediaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAllUpdatablePropertiesEquals(Media expected, Media actual) {
        assertMediaUpdatableFieldsEquals(expected, actual);
        assertMediaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAutoGeneratedPropertiesEquals(Media expected, Media actual) {
        assertThat(expected)
            .as("Verify Media auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaUpdatableFieldsEquals(Media expected, Media actual) {
        assertThat(expected)
            .as("Verify Media relevant properties")
            .satisfies(e -> assertThat(e.getUrl()).as("check url").isEqualTo(actual.getUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaUpdatableRelationshipsEquals(Media expected, Media actual) {
        assertThat(expected)
            .as("Verify Media relationships")
            .satisfies(e -> assertThat(e.getIdentityCard()).as("check identityCard").isEqualTo(actual.getIdentityCard()));
    }
}
